#!/usr/bin/env python3
"""Shared metadata and parsing helpers for KRADFILE components."""

from __future__ import annotations

import re


RADICAL_MEANINGS = {
    "⺅": "person",
    "⺉": "knife",
    "⺌": "small",
    "⺖": "heart",
    "⺘": "hand",
    "⺡": "water",
    "⺣": "fire",
    "⺨": "animal",
    "⺭": "altar",
    "⺲": "net",
    "⺹": "old",
    "⺾": "grass",
    "⻂": "clothing",
    "⻌": "movement",
    "⻏": "village",
    "⻖": "hill",
    "⽧": "sickness",
    "⽱": "tracks",
    "ノ": "slash",
    "ハ": "eight",
    "マ": "ma shape",
    "ユ": "yu shape",
    "ヨ": "hand",
    "一": "one",
    "世": "world",
    "丶": "dot",
    "丷": "horns",
    "久": "long time",
    "乙": "second",
    "九": "nine",
    "也": "also",
    "亅": "hook",
    "二": "two",
    "五": "five",
    "井": "well",
    "亠": "lid",
    "亡": "death",
    "人": "person",
    "儿": "legs",
    "元": "origin",
    "免": "escape",
    "入": "enter",
    "冂": "upside-down box",
    "冊": "book",
    "冖": "cover",
    "冫": "ice",
    "几": "table",
    "凵": "container",
    "刀": "knife",
    "力": "power",
    "勹": "wrap",
    "勿": "must not",
    "匕": "spoon",
    "匚": "box",
    "十": "ten",
    "卜": "divination",
    "卩": "seal",
    "厂": "cliff",
    "厶": "private",
    "又": "again",
    "及": "reach",
    "口": "mouth",
    "品": "goods",
    "啇": "merchant",
    "囗": "enclosure",
    "土": "earth",
    "士": "samurai",
    "夂": "winter",
    "夕": "evening",
    "大": "big",
    "女": "woman",
    "子": "child",
    "宀": "roof",
    "寸": "measure",
    "小": "small",
    "尢": "lame",
    "尸": "corpse",
    "屮": "sprout",
    "屯": "barracks",
    "山": "mountain",
    "川": "river",
    "工": "work",
    "巨": "giant",
    "已": "already",
    "巴": "comma shape",
    "巾": "cloth",
    "干": "dry",
    "幺": "thread",
    "广": "shelter",
    "廴": "long stride",
    "廾": "two hands",
    "弋": "arrow stake",
    "弓": "bow",
    "彑": "pig snout",
    "彡": "hair",
    "彳": "step",
    "心": "heart",
    "戈": "halberd",
    "戸": "door",
    "手": "hand",
    "支": "branch",
    "攵": "strike",
    "文": "writing",
    "斉": "even",
    "斗": "dipper",
    "斤": "axe",
    "方": "direction",
    "日": "sun/day",
    "月": "moon/month",
    "木": "tree",
    "欠": "lack",
    "止": "stop",
    "歯": "tooth",
    "歹": "death",
    "殳": "weapon",
    "毋": "do not",
    "母": "mother",
    "比": "compare",
    "毛": "fur",
    "氏": "clan",
    "气": "steam",
    "水": "water",
    "火": "fire",
    "無": "nothing",
    "爪": "claw",
    "父": "father",
    "爿": "split wood",
    "片": "fragment",
    "牛": "cow",
    "犬": "dog",
    "玄": "mysterious",
    "王": "king",
    "瓦": "tile",
    "甘": "sweet",
    "生": "life",
    "用": "use",
    "田": "rice field",
    "疋": "bolt of cloth",
    "癶": "footsteps",
    "白": "white",
    "皮": "skin",
    "皿": "dish",
    "目": "eye",
    "矛": "spear",
    "矢": "arrow",
    "石": "stone",
    "示": "altar",
    "禾": "grain",
    "穴": "hole",
    "立": "stand",
    "竹": "bamboo",
    "米": "rice",
    "糸": "thread",
    "缶": "jar",
    "羊": "sheep",
    "羽": "feather",
    "耒": "plow",
    "耳": "ear",
    "聿": "brush",
    "肉": "meat",
    "臣": "retainer",
    "自": "self",
    "至": "arrive",
    "舌": "tongue",
    "舛": "opposite feet",
    "舟": "boat",
    "艮": "stopping",
    "色": "color",
    "虍": "tiger",
    "虫": "insect",
    "血": "blood",
    "行": "go",
    "衣": "clothing",
    "西": "west",
    "見": "see",
    "角": "horn",
    "言": "words",
    "谷": "valley",
    "豆": "bean",
    "豕": "pig",
    "貝": "shell",
    "赤": "red",
    "走": "run",
    "足": "foot",
    "身": "body",
    "車": "vehicle",
    "辛": "spicy",
    "辰": "morning",
    "酉": "sake jar",
    "釆": "divide",
    "里": "village",
    "金": "gold/metal",
    "長": "long",
    "門": "gate",
    "隶": "slave",
    "隹": "short-tailed bird",
    "雨": "rain",
    "青": "blue/green",
    "非": "not",
    "面": "face",
    "革": "leather",
    "韋": "tanned leather",
    "音": "sound",
    "頁": "head/page",
    "風": "wind",
    "飛": "fly",
    "食": "eat/food",
    "首": "neck",
    "香": "fragrance",
    "馬": "horse",
    "骨": "bone",
    "高": "tall",
    "髟": "long hair",
    "魚": "fish",
    "鳥": "bird",
    "麦": "wheat",
    "麻": "hemp",
    "黄": "yellow",
    "黒": "black",
    "鼻": "nose",
    "｜": "line",
    "𠂉": "person",
    "𠆢": "person",
}

RADICAL_ENTRY_PATTERN = re.compile(r"^(?P<symbol>.+?) \((?P<meaning>[^()]*)\)$")


def parse_radical_entry(value: str) -> dict[str, str]:
    """Parse one radical component, accepting annotated and legacy forms."""
    value = value.strip()
    match = RADICAL_ENTRY_PATTERN.match(value)
    if match:
        return {
            "symbol": match.group("symbol").strip(),
            "meaning": match.group("meaning").strip(),
        }

    return {"symbol": value, "meaning": RADICAL_MEANINGS.get(value, "")}


def parse_radicals(value: str) -> list[dict[str, str]]:
    return [parse_radical_entry(item) for item in value.split(",") if item.strip()]


def format_radical(symbol: str) -> str:
    return f"{symbol} ({RADICAL_MEANINGS[symbol]})"


def format_radicals(symbols: list[str]) -> str:
    return ", ".join(format_radical(symbol) for symbol in symbols)
